import {
  MAX_CHUNK_BYTES,
  MAX_TRANSCRIPTION_REQUEST_BYTES,
  PREVIOUS_CONTEXT_CHARS,
} from "./transcription-contract.ts";

/** A single speech profile: intelligibility first, comfortably below multipart limits. */
export const TRANSCRIPTION_CONFIG = {
  audio: {
    preferredFormat: "mp3",
    sampleRateHz: 24_000,
    channels: 1,
    bitrateKbps: 48,
  },
  limits: {
    // Admission limits, not a claim that every browser can process this much media.
    maxFileBytes: 1_500_000_000,
    maxDurationSec: 7_200,
    fingerprintSampleBytes: 65_536,
    metadataTimeoutMs: 15_000,
  },
  chunking: {
    targetCoreDurationSec: 300,
    boundarySearchWindowSec: 15,
    minimumSilenceMs: 700,
    silenceNoiseDb: -35,
    prefixBufferSec: 3,
    suffixBufferSec: 3,
    // The remaining Vercel body budget covers multipart metadata and context.
    targetMaxPayloadBytes: MAX_CHUNK_BYTES,
    hardMaxPayloadBytes: MAX_TRANSCRIPTION_REQUEST_BYTES,
    minimumCoreDurationSec: 10,
  },
  merge: {
    previousSuffixWords: 50,
    nextPrefixWords: 50,
    autoRemoveThreshold: 0.88,
    possibleOverlapThreshold: 0.78,
    ambiguousPolicy: "keep",
    minimumMatchChars: 20,
    // A six-second overlap cannot plausibly contain a whole five-minute paragraph.
    maximumWordsPerOverlapSecond: 6,
    maximumCharsPerOverlapSecond: 40,
  },
  context: { previousChunkChars: PREVIOUS_CONTEXT_CHARS },
  retry: { maximumRetries: 3, initialDelayMs: 1_000, maximumDelayMs: 15_000 },
} as const;

export const DEFAULT_AI_KEYWORDS = [
  "OpenAI",
  "ChatGPT",
  "GPT",
  "Codex",
  "NVIDIA",
  "Jensen Huang",
  "Blackwell",
  "Rubin",
  "Vera Rubin",
  "GB200",
  "GB300",
  "NVLink",
  "NVSwitch",
  "CUDA",
  "TensorRT",
  "Transformer",
  "LLM",
  "RAG",
  "Agentic AI",
  "Physical AI",
  "Inference",
  "Training",
  "Fine-tuning",
  "Distillation",
  "GPU",
  "NPU",
  "ASIC",
  "HBM",
  "HBM3E",
  "HBM4",
  "SK hynix",
  "Samsung Electronics",
  "Micron",
  "TSMC",
  "CoWoS",
  "Scale-up",
  "Scale-out",
  "Data Center",
  "Hyperscaler",
];
