import { cleanTranscript, decodeEntities, langMatches, pickTrack } from "./clean";
import type {
  CaptionSourceType,
  CaptionTrack,
  ExtractError,
  ExtractResult,
  Job,
  LangMode,
  ProviderId,
  Segment,
} from "./types";
import { canonicalWatchUrl } from "./parse-url";

const YTAI = "youtube-transcript.ai";
const INNERTUBE = "YouTube Innertube";

const FETCH_MS = 18_000;

function abortAfter(ms: number): AbortSignal {
  return AbortSignal.timeout(ms);
}

async function fetchOk(
  url: string,
  init: RequestInit,
  ms = FETCH_MS,
): Promise<Response> {
  return fetch(url, { ...init, signal: abortAfter(ms) });
}

function classifyPlayability(status?: string, reason?: string): ExtractError | null {
  const s = (status ?? "").toUpperCase();
  const r = (reason ?? "").toLowerCase();
  if (!s && !r) return null;
  if (r.includes("age") || r.includes("inappropriate") || r.includes("confirm your age")) {
    return {
      code: "age_restricted",
      message:
        "This video is age-restricted. YouTube hides captions from unsigned requests. Open it on YouTube while signed in, then More → Show transcript.",
      details: reason,
    };
  }
  if (r.includes("members-only") || r.includes("members only") || r.includes("join this channel")) {
    return {
      code: "members_only",
      message: "This looks members-only. Public caption providers cannot read it.",
      details: reason,
    };
  }
  if (s === "LOGIN_REQUIRED" && r.includes("private")) {
    return {
      code: "unavailable",
      message: "YouTube says this video is private. Public captions are not available.",
      details: reason,
    };
  }
  if (s === "UNPLAYABLE" || s === "ERROR" || r.includes("unavailable") || r.includes("not available")) {
    return {
      code: "unavailable",
      message:
        "YouTube says this video is unavailable. It may be private, deleted, or region-locked.",
      details: reason,
    };
  }
  return null;
}

function languageMissing(want: LangMode, tracks: CaptionTrack[]): ExtractError {
  const available = tracks
    .map((t) => `${t.languageCode}${t.isAutoGenerated ? " (auto)" : ""}`)
    .join(", ");
  const fallback = pickTrack(tracks, "auto");
  const label = want === "ko" ? "Korean" : "English";
  return {
    code: "language_missing",
    message: `No ${label} captions on this video.${available ? ` Available: ${available}.` : ""} Extract a fallback language instead?`,
    availableLanguages: tracks,
    fallbackLang: fallback?.languageCode,
  };
}

function noCaptionsError(): ExtractError {
  return {
    code: "no_captions",
    message:
      "No public captions were found for this video. On YouTube: More → Show transcript → copy, or extract locally with yt-dlp.",
  };
}

function networkError(details?: string): ExtractError {
  return {
    code: "network",
    message: "Network error reaching caption providers. Check your connection and try again.",
    details,
  };
}

function blockedError(details?: string): ExtractError {
  return {
    code: "provider_blocked",
    message:
      "Caption providers were blocked or rate-limited. Wait a moment and retry, or copy the transcript from YouTube (More → Show transcript).",
    details,
  };
}

type RawCapture = {
  title: string;
  language: string;
  sourceType: CaptionSourceType;
  segments: Segment[];
  availableLanguages: CaptionTrack[];
  durationSec: number;
  provider: ProviderId;
  providerLabel: string;
};

function toJob(videoId: string, requestedLang: LangMode, capture: RawCapture): Job {
  const cleaned = cleanTranscript(capture.segments);
  const durationSec =
    capture.durationSec ||
    cleaned.segments.reduce((max, s) => Math.max(max, s.start + s.duration), 0);
  return {
    videoId,
    url: canonicalWatchUrl(videoId),
    title: capture.title || videoId,
    language: capture.language,
    requestedLang,
    sourceType: capture.sourceType,
    provider: capture.provider,
    providerLabel: capture.providerLabel,
    segmentCount: cleaned.segments.length,
    durationSec,
    createdAt: Date.now(),
    segments: cleaned.segments,
    paragraphs: cleaned.paragraphs,
    availableLanguages: capture.availableLanguages,
    summaryKind: "general",
    summary: "",
  };
}

function parseDuration(raw: string): number {
  const parts = raw.trim().split(":").map(Number);
  if (parts.some((n) => !Number.isFinite(n))) return 0;
  if (parts.length === 3) return parts[0]! * 3600 + parts[1]! * 60 + parts[2]!;
  if (parts.length === 2) return parts[0]! * 60 + parts[1]!;
  return Number.isFinite(parts[0]) ? parts[0]! : 0;
}

function parseTimestampToken(token: string): number | null {
  const m = token.match(/^\[(?:(\d{1,2}):)?(\d{1,2}):(\d{2})\]$/);
  if (!m) return null;
  const h = m[1] ? Number(m[1]) : 0;
  const min = Number(m[2]);
  const sec = Number(m[3]);
  return h * 3600 + min * 60 + sec;
}

function parseAvailableLangs(line: string): CaptionTrack[] {
  const tracks: CaptionTrack[] = [];
  const re = /([a-zA-Z][\w-]*)\s*\(([\w-]+)\)(\s*\[auto\])?/g;
  let match: RegExpExecArray | null;
  while ((match = re.exec(line))) {
    const languageCode = match[2] ?? match[1] ?? "und";
    const isAuto = Boolean(match[3]) || (match[1] ?? "").startsWith("a-");
    tracks.push({
      languageCode,
      sourceType: isAuto ? "asr" : "manual",
      isAutoGenerated: isAuto,
    });
  }
  return tracks;
}

function parseYtaiMarkdown(markdown: string, videoId: string): RawCapture | ExtractError {
  const text = markdown.replace(/^\uFEFF/, "");
  if (/transcript unavailable/i.test(text.slice(0, 400))) {
    const reason = text.match(/Reason:\s*(\{[\s\S]*?\}|[^\n]+)/)?.[1] ?? text.slice(0, 280);
    const lower = reason.toLowerCase();
    if (lower.includes("age")) {
      return {
        code: "age_restricted",
        message:
          "This video is age-restricted. YouTube hides captions from unsigned requests. Open it on YouTube while signed in, then More → Show transcript.",
        details: reason,
      };
    }
    if (lower.includes("member")) {
      return {
        code: "members_only",
        message: "This looks members-only. Public caption providers cannot read it.",
        details: reason,
      };
    }
    if (lower.includes("unavailable") || lower.includes("private")) {
      return {
        code: "unavailable",
        message:
          "YouTube says this video is unavailable. It may be private, deleted, or region-locked.",
        details: reason,
      };
    }
    if (lower.includes("caption") || lower.includes("transcript") || lower.includes("subtitle")) {
      return noCaptionsError();
    }
    return {
      code: "unavailable",
      message:
        "The caption provider could not read this video. It may be private, deleted, or missing public captions.",
      details: reason,
    };
  }

  const title =
    text.match(/^#\s*Transcript:\s*(.+)$/m)?.[1]?.trim() ||
    text.match(/^#\s+(.+)$/m)?.[1]?.trim() ||
    videoId;
  const langLine = text.match(/^Language:\s*(.+)$/m)?.[1] ?? "";
  const languageToken = langLine.split(/[·•|,]/)[0]?.trim() ?? "";
  const language = (languageToken.split(/\s+/)[0] || "und").replace(/[^A-Za-z0-9-]/g, "") || "und";
  const isAuto =
    /\[auto\]/i.test(langLine) ||
    /\basr\b/i.test(langLine) ||
    /auto-generated/i.test(langLine);
  const durationToken = langLine.match(/Duration:\s*([\d:]+)/i)?.[1] ?? "";
  const availableLine = text.match(/^Other available languages:\s*(.+)$/m)?.[1] ?? "";
  const availableLanguages = parseAvailableLangs(availableLine);
  if (
    language &&
    !availableLanguages.some((t) => langMatches(t.languageCode, language))
  ) {
    availableLanguages.unshift({
      languageCode: language,
      sourceType: isAuto ? "asr" : "manual",
      isAutoGenerated: isAuto,
    });
  }

  const bodyMatch = text.split(/^##\s*Transcript\s*$/m)[1] ?? text;
  const lines = bodyMatch.split(/\n/);
  const chunks: { start: number; text: string }[] = [];
  let current: { start: number; text: string } | null = null;
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    if (trimmed.startsWith("To request") || trimmed.startsWith("Interactive version")) continue;
    const ts = trimmed.match(/^(\[(?:\d{1,2}:)?\d{1,2}:\d{2}\])\s*(.*)$/);
    if (ts) {
      const start = parseTimestampToken(ts[1] ?? "");
      if (start == null) continue;
      if (current) chunks.push(current);
      current = { start, text: ts[2] ?? "" };
    } else if (current) {
      current.text = `${current.text} ${trimmed}`.trim();
    }
  }
  if (current) chunks.push(current);

  if (chunks.length === 0) {
    const fallback = bodyMatch
      .replace(/^#.+$/gm, "")
      .replace(/^Source video:.*$/gm, "")
      .replace(/^Language:.*$/gm, "")
      .replace(/^Other available.*$/gm, "")
      .replace(/^To request.*$/gm, "")
      .replace(/^Interactive version.*$/gm, "")
      .replace(/^##\s*Transcript\s*$/gm, "")
      .trim();
    if (!fallback) return noCaptionsError();
    chunks.push({ start: 0, text: fallback });
  }

  const durationSec = parseDuration(durationToken);
  const segments: Segment[] = chunks.map((chunk, i) => {
    const next = chunks[i + 1];
    const duration = next ? Math.max(0.4, next.start - chunk.start) : Math.max(0.4, 4);
    return { start: chunk.start, duration, text: chunk.text };
  });

  return {
    title,
    language,
    sourceType: isAuto ? "asr" : "manual",
    segments,
    availableLanguages,
    durationSec,
    provider: "youtube-transcript.ai",
    providerLabel: YTAI,
  };
}

async function fetchYtaiOnce(
  videoId: string,
  attempt: string | undefined,
): Promise<RawCapture | ExtractError | "network"> {
  const url = attempt
    ? `https://youtube-transcript.ai/transcript/${videoId}.txt?lang=${encodeURIComponent(attempt)}`
    : `https://youtube-transcript.ai/transcript/${videoId}.txt`;
  try {
    const res = await fetchOk(
      url,
      {
        headers: {
          Accept: "text/markdown, text/plain; q=0.9, */*; q=0.1",
        },
      },
      14_000,
    );
    if (res.status === 429 || res.status === 403) {
      return blockedError(`youtube-transcript.ai HTTP ${res.status}`);
    }
    const body = await res.text();
    if (!body.trim()) return "network";
    return parseYtaiMarkdown(body, videoId);
  } catch (err) {
    if (err instanceof DOMException && err.name === "TimeoutError") {
      return "network";
    }
    return "network";
  }
}

function isHardFail(error: ExtractError): boolean {
  return (
    error.code === "unavailable" ||
    error.code === "age_restricted" ||
    error.code === "members_only" ||
    error.code === "provider_blocked"
  );
}

async function providerYtai(
  videoId: string,
  lang: LangMode,
): Promise<RawCapture | ExtractError | "network"> {
  if (lang === "auto") {
    const fallback = await fetchYtaiOnce(videoId, undefined);
    if (fallback !== "network" && "code" in fallback) {
      if (isHardFail(fallback)) return fallback;
    } else if (fallback !== "network") {
      if (langMatches(fallback.language, "ko")) return fallback;
      const hasKo = fallback.availableLanguages.some((t) =>
        langMatches(t.languageCode, "ko"),
      );
      if (hasKo) {
        const ko = await fetchYtaiOnce(videoId, "ko");
        if (ko !== "network" && !("code" in ko) && langMatches(ko.language, "ko")) {
          return ko;
        }
      }
      if (langMatches(fallback.language, "en")) return fallback;
      const hasEn = fallback.availableLanguages.some((t) =>
        langMatches(t.languageCode, "en"),
      );
      if (hasEn && !langMatches(fallback.language, "en")) {
        const en = await fetchYtaiOnce(videoId, "en");
        if (en !== "network" && !("code" in en) && langMatches(en.language, "en")) {
          return en;
        }
      }
      return fallback;
    }
  }

  const langsToTry: Array<string | undefined> =
    lang === "auto" ? ["ko", "en", undefined] : [lang];
  let last: RawCapture | ExtractError | "network" | null = null;
  const seen = new Set<string>();

  for (const attempt of langsToTry) {
    const key = attempt ?? "*";
    if (seen.has(key)) continue;
    seen.add(key);
    const parsed = await fetchYtaiOnce(videoId, attempt);
    last = parsed;
    if (parsed !== "network" && "code" in parsed) {
      if (isHardFail(parsed)) return parsed;
      continue;
    }
    if (parsed === "network") continue;
    if (lang !== "auto" && !langMatches(parsed.language, lang)) {
      continue;
    }
    if (lang === "auto" && attempt === "ko" && !langMatches(parsed.language, "ko")) {
      continue;
    }
    return parsed;
  }

  if (last && last !== "network" && !("code" in last)) {
    if (lang !== "auto" && !langMatches(last.language, lang)) {
      return languageMissing(lang, last.availableLanguages);
    }
    return last;
  }
  if (last && last !== "network" && "code" in last) return last;
  return "network";
}

type InnertubeTrack = {
  baseUrl: string;
  languageCode: string;
  kind?: string;
  name?: { simpleText?: string } | string;
};

type InnertubePlayer = {
  playabilityStatus?: { status?: string; reason?: string };
  videoDetails?: { title?: string; lengthSeconds?: string };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: InnertubeTrack[];
    };
  };
};

function trackName(track: InnertubeTrack): string | undefined {
  if (typeof track.name === "string") return track.name;
  return track.name?.simpleText;
}

function mapInnertubeTracks(tracks: InnertubeTrack[]): CaptionTrack[] {
  return tracks.map((t) => {
    const asr = t.kind === "asr";
    return {
      languageCode: t.languageCode || "und",
      languageName: trackName(t),
      sourceType: asr ? "asr" : "manual",
      isAutoGenerated: asr,
    };
  });
}

function pickInnertubeTrack(
  tracks: InnertubeTrack[],
  requested: LangMode,
): InnertubeTrack | null {
  const mapped = mapInnertubeTracks(tracks);
  const chosen = pickTrack(mapped, requested);
  if (!chosen) return null;
  return (
    tracks.find((t) => {
      const asr = t.kind === "asr";
      return (
        langMatches(t.languageCode, chosen.languageCode) &&
        (asr ? "asr" : "manual") === chosen.sourceType
      );
    }) ?? null
  );
}

function withJson3(baseUrl: string): string {
  if (/[?&]fmt=/.test(baseUrl)) return baseUrl.replace(/([?&]fmt=)[^&]*/i, "$1json3");
  return `${baseUrl}${baseUrl.includes("?") ? "&" : "?"}fmt=json3`;
}

function parseJson3(payload: string): Segment[] {
  const data = JSON.parse(payload) as {
    events?: Array<{ tStartMs?: number; dDurationMs?: number; segs?: Array<{ utf8?: string }> }>;
  };
  const segments: Segment[] = [];
  for (const event of data.events ?? []) {
    const segs = event.segs ?? [];
    const text = segs
      .map((s) => s.utf8 ?? "")
      .filter((s) => s && s !== "\n")
      .join("");
    const trimmed = text.replace(/\s+/g, " ").trim();
    if (!trimmed) continue;
    segments.push({
      start: (event.tStartMs ?? 0) / 1000,
      duration: (event.dDurationMs ?? 1000) / 1000,
      text: trimmed,
    });
  }
  return segments;
}

function parseTimedtextXml(xml: string): Segment[] {
  const segments: Segment[] = [];
  const re = /<p\b([^>]*)>([\s\S]*?)<\/p>/gi;
  let match: RegExpExecArray | null;
  while ((match = re.exec(xml))) {
    const attrs = match[1] ?? "";
    const t = Number(attrs.match(/\bt="(\d+)"/)?.[1] ?? "0");
    const d = Number(attrs.match(/\bd="(\d+)"/)?.[1] ?? "1000");
    const inner = (match[2] ?? "")
      .replace(/<s\b[^>]*>/gi, "")
      .replace(/<\/s>/gi, "")
      .replace(/<br\s*\/?>/gi, " ")
      .replace(/<[^>]+>/g, "");
    const text = decodeEntities(inner).replace(/\s+/g, " ").trim();
    if (!text) continue;
    segments.push({ start: t / 1000, duration: d / 1000, text });
  }
  return segments;
}

export async function extractViaYtai(
  videoId: string,
  lang: LangMode,
): Promise<ExtractResult | null> {
  const first = await providerYtai(videoId, lang);
  if (first !== "network" && !("code" in first)) {
    if (lang !== "auto" && !langMatches(first.language, lang)) {
      return null;
    }
    return { ok: true, job: toJob(videoId, lang, first) };
  }
  return null;
}

const BROWSER_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

function extractJsonAfter(html: string, token: string): unknown | null {
  const i = html.indexOf(token);
  if (i < 0) return null;
  const start = html.indexOf("{", i);
  if (start < 0) return null;
  let depth = 0;
  let inStr = false;
  let esc = false;
  for (let j = start; j < html.length; j++) {
    const ch = html[j]!;
    if (inStr) {
      if (esc) {
        esc = false;
        continue;
      }
      if (ch === "\\") {
        esc = true;
        continue;
      }
      if (ch === '"') inStr = false;
      continue;
    }
    if (ch === '"') {
      inStr = true;
      continue;
    }
    if (ch === "{") depth += 1;
    else if (ch === "}") {
      depth -= 1;
      if (depth === 0) {
        try {
          return JSON.parse(html.slice(start, j + 1));
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}

async function postInnertube(
  videoId: string,
  clientName: string,
  clientVersion: string,
  extra: Record<string, unknown> = {},
): Promise<InnertubePlayer | null> {
  try {
    const res = await fetchOk(
      "https://www.youtube.com/youtubei/v1/player?prettyPrint=false",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "User-Agent": BROWSER_UA,
        },
        body: JSON.stringify({
          context: {
            client: {
              clientName,
              clientVersion,
              hl: "en",
              gl: "US",
              ...extra,
            },
          },
          videoId,
        }),
      },
      14_000,
    );
    if (res.status === 429 || res.status === 403) return null;
    if (!res.ok) return null;
    return (await res.json()) as InnertubePlayer;
  } catch {
    return null;
  }
}

async function playerFromWatchPage(videoId: string): Promise<InnertubePlayer | null> {
  try {
    const res = await fetchOk(
      `https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}&hl=en`,
      {
        headers: {
          "User-Agent": BROWSER_UA,
          Accept: "text/html,application/xhtml+xml",
        },
      },
      14_000,
    );
    if (!res.ok) return null;
    const html = await res.text();
    const parsed = extractJsonAfter(html, "ytInitialPlayerResponse");
    if (parsed && typeof parsed === "object") return parsed as InnertubePlayer;
    return null;
  } catch {
    return null;
  }
}

async function loadPlayer(videoId: string): Promise<InnertubePlayer | ExtractError> {
  const vr = await postInnertube(videoId, "ANDROID_VR", "1.57.29", {
    androidSdkVersion: 32,
  });
  if (vr?.captions?.playerCaptionsTracklistRenderer?.captionTracks?.length) return vr;

  const web = await postInnertube(videoId, "WEB", "2.20240101.00.00");
  if (web?.captions?.playerCaptionsTracklistRenderer?.captionTracks?.length) return web;

  const page = await playerFromWatchPage(videoId);
  if (page) return page;

  if (vr) return vr;
  if (web) return web;
  return blockedError("Innertube and the watch page returned no player payload.");
}

async function providerInnertube(
  videoId: string,
  lang: LangMode,
): Promise<RawCapture | ExtractError> {
  const playerOrErr = await loadPlayer(videoId);
  if ("code" in playerOrErr) {
    return playerOrErr;
  }
  const player = playerOrErr;

  const playability = classifyPlayability(
    player.playabilityStatus?.status,
    player.playabilityStatus?.reason,
  );
  const tracks = player.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  const mapped = mapInnertubeTracks(tracks);
  const title = player.videoDetails?.title || videoId;
  const durationSec = Number(player.videoDetails?.lengthSeconds ?? 0);

  if (tracks.length === 0) {
    return playability ?? noCaptionsError();
  }

  const chosen = pickInnertubeTrack(tracks, lang);
  if (!chosen) {
    if (lang !== "auto") return languageMissing(lang, mapped);
    return noCaptionsError();
  }

  if (lang !== "auto" && !langMatches(chosen.languageCode, lang)) {
    return languageMissing(lang, mapped);
  }

  const timedtextUrl = withJson3(chosen.baseUrl);
  try {
    const capRes = await fetchOk(
      timedtextUrl,
      {
        headers: {
          "User-Agent":
            "com.google.android.apps.youtube.vr.oculus/1.57.29 (Linux; U; Android 12; XR)",
          Accept: "application/json, text/xml; q=0.9, */*; q=0.1",
        },
      },
      16_000,
    );
    if (!capRes.ok) {
      return blockedError(`timedtext HTTP ${capRes.status}`);
    }
    const body = await capRes.text();
    if (!body.trim()) {
      return blockedError("timedtext returned an empty body (likely bot-check / PO token).");
    }
    let segments: Segment[] = [];
    const trimmed = body.trim();
    if (trimmed.startsWith("{")) {
      try {
        segments = parseJson3(trimmed);
      } catch {
        segments = [];
      }
    }
    if (segments.length === 0 && trimmed.startsWith("<")) {
      segments = parseTimedtextXml(trimmed);
    }
    if (segments.length === 0) return noCaptionsError();
    const asr = chosen.kind === "asr";
    return {
      title,
      language: chosen.languageCode,
      sourceType: asr ? "asr" : "manual",
      segments,
      availableLanguages: mapped,
      durationSec,
      provider: "innertube",
      providerLabel: INNERTUBE,
    };
  } catch (err) {
    return networkError(err instanceof Error ? err.message : "timedtext failed");
  }
}

export async function runWaterfall(
  videoId: string,
  lang: LangMode,
): Promise<ExtractResult> {
  const first = await providerYtai(videoId, lang);
  if (first !== "network" && !("code" in first)) {
    if (lang !== "auto" && !langMatches(first.language, lang)) {
      return { ok: false, error: languageMissing(lang, first.availableLanguages) };
    }
    return { ok: true, job: toJob(videoId, lang, first) };
  }

  const second = await providerInnertube(videoId, lang);
  if (!("code" in second)) {
    return { ok: true, job: toJob(videoId, lang, second) };
  }

  if (first !== "network" && "code" in first) {
    if (first.code === "language_missing" && second.code === "language_missing") {
      return { ok: false, error: second };
    }
    if (first.code !== "network") {
      // Prefer the more specific of the two failures.
      if (second.code === "no_captions" || second.code === "language_missing") {
        return { ok: false, error: second };
      }
      return { ok: false, error: first };
    }
  }

  return { ok: false, error: second };
}
