import assert from "node:assert/strict";
import { afterEach, beforeEach, describe, it } from "node:test";
import { IDBFactory, IDBObjectStore } from "fake-indexeddb";
import {
  deleteJob,
  exportBackup,
  getSettings,
  importBackup,
  jobIdentity,
  loadJobs,
  saveJob,
  saveJobs,
  setSettings,
  StorageError,
  upsertJob,
  validateBackup,
} from "./storage.ts";
import type { Job } from "./types.ts";

function memoryStorage(): Storage {
  const entries = new Map<string, string>();
  return {
    get length() {
      return entries.size;
    },
    getItem: (key) => entries.get(key) ?? null,
    setItem: (key, value) => {
      entries.set(key, value);
    },
    removeItem: (key) => {
      entries.delete(key);
    },
    clear: () => {
      entries.clear();
    },
    key: (index) => [...entries.keys()][index] ?? null,
  };
}

function youtube(overrides: Partial<Job> = {}): Job {
  return {
    videoId: "video123",
    url: "https://www.youtube.com/watch?v=video123",
    title: "기존 인터뷰",
    language: "ko",
    requestedLang: "ko",
    sourceType: "manual",
    provider: "innertube",
    providerLabel: "YouTube",
    segmentCount: 1,
    durationSec: 4,
    createdAt: 10,
    segments: [{ start: 0, duration: 4, text: "Hello 안녕하세요", speaker: "진행자" }],
    paragraphs: [
      { start: 0, duration: 4, text: "직접 편집한 본문", speaker: "진행자", turnMark: true },
    ],
    availableLanguages: [{ languageCode: "ko", sourceType: "manual", isAutoGenerated: false }],
    summaryKind: "interview",
    summary: "직접 편집한 요약",
    speakers: ["진행자"],
    ...overrides,
  };
}

function upload(overrides: Partial<Job> = {}): Job {
  const { videoId: _videoId, url: _url, ...base } = youtube();
  return {
    ...base,
    id: "upload-job",
    source: {
      kind: "upload",
      fileName: "conference.mp4",
      mimeType: "video/mp4",
      sizeBytes: 1_000_000_000,
      lastModified: 12,
      fingerprint: "sha256-file",
    },
    provider: "openai",
    providerLabel: "OpenAI",
    sourceType: "transcription",
    timestampQuality: "chunk-estimated",
    upload: {
      status: "cancelled",
      settings: {
        language: "ko-en",
        contentMode: "ai-conference",
        keywords: ["Transformer", "삼성"],
      },
      plan: [{ id: "chunk-0", index: 0, coreStart: 0, coreEnd: 20, start: 0, end: 22 }],
      chunks: [
        {
          id: "chunk-0",
          index: 0,
          coreStart: 0,
          coreEnd: 20,
          start: 0,
          end: 22,
          completedAt: 15,
          sizeBytes: 40_000,
          transcript: { text: "Transformer 발표", timestampQuality: "chunk-estimated" },
        },
      ],
    },
    ...overrides,
  };
}

async function writeRawSetting(key: string, value: unknown): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const request = indexedDB.open("intertext");
    request.onerror = () => reject(request.error);
    request.onsuccess = () => {
      const database = request.result;
      const transaction = database.transaction("settings", "readwrite");
      transaction.objectStore("settings").put({ key, value });
      transaction.oncomplete = () => {
        database.close();
        resolve();
      };
      transaction.onabort = () => {
        database.close();
        reject(transaction.error);
      };
    };
  });
}

const originalIndexedDB = Object.getOwnPropertyDescriptor(globalThis, "indexedDB");
const originalStorage = Object.getOwnPropertyDescriptor(globalThis, "localStorage");
let local: Storage;
beforeEach(() => {
  Object.defineProperty(globalThis, "indexedDB", { configurable: true, value: new IDBFactory() });
  local = memoryStorage();
  Object.defineProperty(globalThis, "localStorage", { configurable: true, value: local });
});
afterEach(() => {
  if (originalIndexedDB) Object.defineProperty(globalThis, "indexedDB", originalIndexedDB);
  else Reflect.deleteProperty(globalThis, "indexedDB");
  if (originalStorage) Object.defineProperty(globalThis, "localStorage", originalStorage);
  else Reflect.deleteProperty(globalThis, "localStorage");
});

describe("local IndexedDB transcript history", () => {
  it("migrates both legacy versions, preserves all fields, and prefers v2 duplicates", async () => {
    const old = youtube({ title: "old v1" });
    const current = { ...youtube(), customManualEdit: "keep this field" };
    const english = youtube({ language: "en", title: "English talk" });
    local.setItem("intertext.jobs.v1", JSON.stringify([old, english]));
    local.setItem("intertext.jobs.v2", JSON.stringify([current]));
    const migrated = await loadJobs();
    assert.equal(migrated.length, 2);
    const korean = migrated.find((job) => job.language === "ko")!;
    assert.equal(korean.title, current.title);
    assert.deepEqual(korean.segments, current.segments);
    assert.deepEqual(korean.paragraphs, current.paragraphs);
    assert.equal(korean.summary, current.summary);
    assert.equal(
      (korean as Job & { customManualEdit: string }).customManualEdit,
      "keep this field",
    );
    assert.deepEqual(korean.source, {
      kind: "youtube",
      videoId: current.videoId,
      url: current.url,
    });
    assert.equal(local.getItem("intertext.jobs.v1"), null);
    assert.equal(local.getItem("intertext.jobs.v2"), null);
    assert.equal((await loadJobs()).length, 2);
  });

  it("does not overwrite edited jobs when legacy cleanup is blocked", async (test) => {
    local.setItem("intertext.jobs.v2", JSON.stringify([youtube()]));
    test.mock.method(local, "removeItem", () => {
      throw new DOMException("blocked", "SecurityError");
    });
    const [first] = await loadJobs();
    await saveJob({ ...first!, title: "Renamed", summary: "Edited after migration" });
    const again = await loadJobs();
    assert.equal(again.length, 1);
    assert.equal(again[0]!.title, "Renamed");
    assert.equal(again[0]!.summary, "Edited after migration");
    assert.notEqual(local.getItem("intertext.jobs.v2"), null);
    assert.deepEqual(JSON.parse(await exportBackup()).settings, {});
  });

  it("keeps legacy data and rolls back the migration when quota is exhausted", async (test) => {
    const already = youtube({ id: "already", title: "already saved" });
    await saveJob(already);
    const raw = JSON.stringify([youtube({ title: "quota" })]);
    local.setItem("intertext.jobs.v1", raw);
    const put = IDBObjectStore.prototype.put;
    const mock = test.mock.method(
      IDBObjectStore.prototype,
      "put",
      function (this: IDBObjectStore, value: unknown, key?: IDBValidKey) {
        if (this.name === "jobs" && (value as Job).title === "quota")
          throw new DOMException("full", "QuotaExceededError");
        return put.call(this, value, key);
      },
    );
    await assert.rejects(
      loadJobs(),
      (error: unknown) => error instanceof StorageError && error.code === "storage_quota",
    );
    assert.equal(local.getItem("intertext.jobs.v1"), raw);
    mock.mock.restore();
    const recovered = await loadJobs();
    assert.equal(recovered.length, 2);
    assert.equal(recovered.find((job) => job.id === "already")!.title, "already saved");
    assert.equal(local.getItem("intertext.jobs.v1"), null);
  });

  it("does not resurrect deleted legacy jobs, but recovers newly added records", async (test) => {
    local.setItem("intertext.jobs.v2", JSON.stringify([youtube()]));
    test.mock.method(local, "removeItem", () => {
      throw new DOMException("blocked", "SecurityError");
    });
    const [first] = await loadJobs();
    await deleteJob(jobIdentity(first!));
    assert.deepEqual(await loadJobs(), []);
    local.setItem(
      "intertext.jobs.v2",
      JSON.stringify([youtube(), youtube({ videoId: "another123", title: "New legacy record" })]),
    );
    const recovered = await loadJobs();
    assert.equal(recovered.length, 1);
    assert.equal(recovered[0]!.title, "New legacy record");
  });

  it("does not silently drop malformed legacy history", async () => {
    local.setItem("intertext.jobs.v2", "not json");
    await assert.rejects(
      loadJobs(),
      (error: unknown) => error instanceof StorageError && error.code === "invalid_history",
    );
    assert.equal(local.getItem("intertext.jobs.v2"), "not json");
  });

  it("stores and resumes upload checkpoints without a fake YouTube ID", async () => {
    const job = upload();
    await saveJob(job);
    await setSettings("processing", job.upload!.settings);
    const [loaded] = await loadJobs();
    assert.equal(loaded!.videoId, undefined);
    assert.equal(loaded!.url, undefined);
    assert.deepEqual(loaded!.upload, job.upload);
    assert.deepEqual(await getSettings("processing"), job.upload!.settings);
    assert.equal(await getSettings("missing"), undefined);
    await deleteJob(jobIdentity(loaded!));
    assert.deepEqual(await loadJobs(), []);
  });

  it("validates known upload settings on writes and reads without destroying saved data", async () => {
    const valid = upload().upload!.settings;
    await setSettings("upload", valid);
    const invalidSettings = [
      { ...valid, keywords: undefined },
      { ...valid, keywords: ["valid", 123] },
      { ...valid, language: "unsupported" },
      { ...valid, contentMode: "unknown-mode" },
      { ...valid, prompt: { text: "not a string" } },
      null,
    ];
    for (const value of invalidSettings) {
      await assert.rejects(setSettings("upload", value), { code: "invalid_history" });
      assert.deepEqual(await getSettings("upload"), valid);
    }
    const corrupt = { language: "auto", contentMode: "speech", keywords: "not an array" };
    await writeRawSetting("upload", corrupt);
    await assert.rejects(getSettings("upload"), { code: "invalid_history" });
    // A rejected read leaves the record in place; it does not silently erase browser settings.
    await assert.rejects(getSettings("upload"), { code: "invalid_history" });
    await setSettings("upload", valid);
    assert.deepEqual(await getSettings("upload"), valid);
  });

  it("preserves valid manual edits and rejects malformed edit maps before saving", async () => {
    const job = upload({
      paragraphEdits: {
        "0": { text: "Corrected", speaker: undefined },
        "12.5": { text: "", speaker: "Presenter" },
      },
    });
    await saveJob(job);
    assert.deepEqual((await loadJobs())[0]!.paragraphEdits, job.paragraphEdits);
    const malformed: unknown[] = [
      { "-1": { text: "negative timestamp" } },
      { "00": { text: "noncanonical timestamp" } },
      { constructor: { text: "reserved property" } },
      { "0": { text: 123 } },
      { "0": { text: "valid", speaker: null } },
      { "0": { text: "valid", start: -1 } },
      ["not a map"],
    ];
    for (const paragraphEdits of malformed) {
      await assert.rejects(
        saveJob({ ...job, title: "Should not replace", paragraphEdits } as unknown as Job),
        { code: "invalid_history" },
      );
      assert.equal((await loadJobs())[0]!.title, job.title);
      assert.deepEqual((await loadJobs())[0]!.paragraphEdits, job.paragraphEdits);
    }
  });

  it("retains more than ten jobs and updates lists without triggering storage writes", async () => {
    const jobs = Array.from({ length: 15 }, (_, index) =>
      youtube({ id: `job-${index}`, createdAt: index }),
    );
    await saveJobs(jobs);
    const loaded = await loadJobs();
    assert.equal(loaded.length, 15);
    assert.equal(loaded[0]!.id, "job-14");
    const edited = upsertJob(loaded, { ...loaded[0]!, title: "unsaved change" });
    assert.equal(edited.length, 15);
    assert.equal(edited[0]!.title, "unsaved change");
    assert.equal((await loadJobs())[0]!.title, jobs[14]!.title);
    assert.equal(jobIdentity(youtube()), jobIdentity(youtube({ title: "renamed" })));
    assert.notEqual(
      jobIdentity(upload({ id: undefined })),
      jobIdentity(upload({ id: undefined, createdAt: 11 })),
    );
  });

  it("keeps all previous jobs when a save transaction hits quota", async (test) => {
    await saveJob(youtube({ id: "keep", title: "keep" }));
    const put = IDBObjectStore.prototype.put;
    test.mock.method(
      IDBObjectStore.prototype,
      "put",
      function (this: IDBObjectStore, value: unknown, key?: IDBValidKey) {
        if (this.name === "jobs" && (value as Job).title === "quota")
          throw new DOMException("full", "QuotaExceededError");
        return put.call(this, value, key);
      },
    );
    await assert.rejects(
      saveJobs([
        youtube({ id: "first", title: "first" }),
        youtube({ id: "quota", title: "quota" }),
      ]),
      (error: unknown) => error instanceof StorageError && error.code === "storage_quota",
    );
    assert.deepEqual(
      (await loadJobs()).map((job) => job.id),
      ["keep"],
    );
  });
});

describe("INTERTEXT backup", () => {
  it("round trips transcripts, edits, checkpoints, and settings without media binary", async () => {
    const job = upload();
    await saveJobs([job, youtube()]);
    await setSettings("processing", job.upload!.settings);
    await setSettings("editor", { fontSize: 18, timestampMode: "off" });
    const json = await exportBackup();
    const backup = validateBackup(json);
    assert.equal(backup.jobs.length, 2);
    assert.equal(backup.jobs.find((entry) => entry.id === job.id)!.source!.kind, "upload");
    assert.equal(json.includes('"blob"'), false);
    await deleteJob(job.id!);
    await setSettings("editor", { fontSize: 12 });
    assert.deepEqual(await importBackup(json), { jobs: 2, settings: 2 });
    assert.deepEqual(
      (await loadJobs()).find((entry) => entry.id === job.id),
      job,
    );
    assert.deepEqual(await getSettings("editor"), { fontSize: 18, timestampMode: "off" });
  });

  it("validates the entire backup before changing any history or settings", async () => {
    await saveJob(youtube());
    await setSettings("editor", { fontSize: 18 });
    const backup = JSON.parse(await exportBackup());
    backup.jobs.push({ ...upload(), segments: [{ start: -1, duration: 2, text: "bad" }] });
    backup.settings.editor.fontSize = 99;
    await assert.rejects(
      importBackup(JSON.stringify(backup)),
      (error: unknown) => error instanceof StorageError && error.code === "invalid_backup",
    );
    assert.equal((await loadJobs()).length, 1);
    assert.deepEqual(await getSettings("editor"), { fontSize: 18 });
    assert.throws(() => validateBackup("not-json"), { code: "invalid_backup" });
    assert.throws(
      () => validateBackup({ format: "intertext-backup", version: 999, jobs: [], settings: {} }),
      { code: "invalid_backup" },
    );
    const valid = JSON.parse(await exportBackup());
    assert.throws(() => validateBackup({ ...valid, jobs: [youtube(), youtube()] }), {
      code: "invalid_backup",
    });
  });

  it("rolls back jobs and settings together when backup import cannot commit", async (test) => {
    await saveJob(youtube({ id: "keep", title: "keep" }));
    await setSettings("editor", { fontSize: 18 });
    const put = IDBObjectStore.prototype.put;
    test.mock.method(
      IDBObjectStore.prototype,
      "put",
      function (this: IDBObjectStore, value: unknown, key?: IDBValidKey) {
        if (this.name === "settings" && (value as { key: string }).key === "fail")
          throw new DOMException("full", "QuotaExceededError");
        return put.call(this, value, key);
      },
    );
    const backup = {
      format: "intertext-backup",
      version: 1,
      jobs: [upload()],
      settings: { editor: { fontSize: 99 }, fail: true },
    };
    await assert.rejects(
      importBackup(backup),
      (error: unknown) => error instanceof StorageError && error.code === "storage_quota",
    );
    assert.deepEqual(
      (await loadJobs()).map((job) => job.id),
      ["keep"],
    );
    assert.deepEqual(await getSettings("editor"), { fontSize: 18 });
  });

  it("rejects malformed upload settings and paragraph edits before any backup changes", async () => {
    const saved = youtube({ id: "keep" });
    const settings = upload().upload!.settings;
    await saveJob(saved);
    await setSettings("upload", settings);
    await setSettings("editor", { fontSize: 18 });
    const valid = {
      format: "intertext-backup",
      version: 1,
      jobs: [upload()],
      settings: { upload: settings, editor: { fontSize: 99 } },
    };
    const invalidBackups = [
      { ...valid, settings: { ...valid.settings, upload: { ...settings, keywords: "bad" } } },
      { ...valid, settings: { ...valid.settings, upload: { ...settings, language: "invalid" } } },
      {
        ...valid,
        jobs: [upload({ paragraphEdits: { "0": { text: 123 } } } as unknown as Partial<Job>)],
      },
      { ...valid, jobs: [upload({ paragraphEdits: { NaN: { text: "bad key" } } })] },
    ];
    for (const backup of invalidBackups) {
      await assert.rejects(importBackup(JSON.stringify(backup)), { code: "invalid_backup" });
      assert.deepEqual(
        (await loadJobs()).map((job) => job.id),
        ["keep"],
      );
      assert.deepEqual(await getSettings("upload"), settings);
      assert.deepEqual(await getSettings("editor"), { fontSize: 18 });
    }
    assert.deepEqual(await importBackup(valid), { jobs: 1, settings: 2 });
  });

  it("rejects original media files in settings and unknown job fields", async () => {
    await assert.rejects(setSettings("media", new Blob(["audio"])), { code: "invalid_history" });
    await assert.rejects(saveJob({ ...upload(), originalMedia: new Uint8Array([1, 2]) } as Job), {
      code: "invalid_history",
    });
    assert.deepEqual(await loadJobs(), []);
  });
});
