import type { MediaSource, TimestampQuality, UploadState } from "./media-types.ts";

export type LangMode = "auto" | "ko" | "en";

export type SummaryKind =
  "general" | "meeting" | "course" | "interview" | "podcast" | "ai-conference";

export const SUMMARY_KINDS: ReadonlyArray<{
  id: SummaryKind;
  label: string;
  hint: string;
}> = [
  { id: "general", label: "General", hint: "Overview of the whole talk" },
  { id: "meeting", label: "Meeting", hint: "Topics, decisions, action items" },
  { id: "course", label: "Course", hint: "Outline and key takeaways" },
  { id: "interview", label: "Interview", hint: "Host and guest, using their names" },
  { id: "podcast", label: "Podcast", hint: "Episode notes and highlights" },
  {
    id: "ai-conference",
    label: "AI conference",
    hint: "Session topics, technical terms, and key takeaways",
  },
];

export function isSummaryKind(value: string): value is SummaryKind {
  return SUMMARY_KINDS.some((k) => k.id === value);
}

export type ExtractInput = {
  videoId: string;
  lang: LangMode;
};

export type CaptionSourceType = "manual" | "asr" | "transcription";

export type TimestampMode = "off" | "inline" | "srt";

export type ProviderId = "youtube-transcript.ai" | "innertube" | "openai";

export type VideoRef = {
  videoId: string;
  canonicalUrl: string;
  originalInput: string;
};

export type CaptionTrack = {
  languageCode: string;
  languageName?: string;
  sourceType: CaptionSourceType;
  isAutoGenerated: boolean;
};

export type Segment = {
  start: number;
  duration: number;
  text: string;
  speaker?: string;
};

export type Paragraph = {
  start: number;
  duration: number;
  text: string;
  speaker?: string;
  turnMark?: boolean;
};

export type Job = {
  id?: string;
  source?: MediaSource;
  upload?: UploadState;
  timestampQuality?: TimestampQuality;
  paragraphEdits?: Record<string, { text: string; speaker?: string }>;
  videoId?: string;
  url?: string;
  title: string;
  language: string;
  requestedLang: LangMode;
  sourceType: CaptionSourceType;
  provider: ProviderId;
  providerLabel: string;
  segmentCount: number;
  durationSec: number;
  createdAt: number;
  segments: Segment[];
  paragraphs: Paragraph[];
  availableLanguages: CaptionTrack[];
  summaryKind: SummaryKind;
  summary: string;
  speakers?: string[];
  summarySource?: "model" | "fallback";
};

export type ExtractErrorCode =
  | "invalid_url"
  | "no_captions"
  | "age_restricted"
  | "members_only"
  | "provider_blocked"
  | "network"
  | "language_missing"
  | "unavailable";

export type ExtractError = {
  code: ExtractErrorCode;
  message: string;
  details?: string;
  availableLanguages?: CaptionTrack[];
  fallbackLang?: string;
};

export type ExtractOk = {
  ok: true;
  job: Job;
};

export type ExtractFail = {
  ok: false;
  error: ExtractError;
};

export type ExtractResult = ExtractOk | ExtractFail;
