/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSlidesRouteImport } from './routes/api/slides'
import { Route as ApiSlidesConfigRouteImport } from './routes/api/slides-config'
import { Route as ApiTranscriptionRouteImport } from './routes/api/transcription'
import { Route as ApiTranscriptionConfigRouteImport } from './routes/api/transcription-config'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlidesRoute = ApiSlidesRouteImport.update({
  id: '/api/slides',
  path: '/api/slides',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlidesConfigRoute = ApiSlidesConfigRouteImport.update({
  id: '/api/slides-config',
  path: '/api/slides-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscriptionRoute = ApiTranscriptionRouteImport.update({
  id: '/api/transcription',
  path: '/api/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscriptionConfigRoute = ApiTranscriptionConfigRouteImport.update({
  id: '/api/transcription-config',
  path: '/api/transcription-config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/slides': typeof ApiSlidesRoute
  '/api/slides-config': typeof ApiSlidesConfigRoute
  '/api/transcription': typeof ApiTranscriptionRoute
  '/api/transcription-config': typeof ApiTranscriptionConfigRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/slides': typeof ApiSlidesRoute
  '/api/slides-config': typeof ApiSlidesConfigRoute
  '/api/transcription': typeof ApiTranscriptionRoute
  '/api/transcription-config': typeof ApiTranscriptionConfigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/slides': typeof ApiSlidesRoute
  '/api/slides-config': typeof ApiSlidesConfigRoute
  '/api/transcription': typeof ApiTranscriptionRoute
  '/api/transcription-config': typeof ApiTranscriptionConfigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/slides'
    | '/api/slides-config'
    | '/api/transcription'
    | '/api/transcription-config'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/slides'
    | '/api/slides-config'
    | '/api/transcription'
    | '/api/transcription-config'
  id:
    | '__root__'
    | '/'
    | '/api/slides'
    | '/api/slides-config'
    | '/api/transcription'
    | '/api/transcription-config'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSlidesRoute: typeof ApiSlidesRoute
  ApiSlidesConfigRoute: typeof ApiSlidesConfigRoute
  ApiTranscriptionRoute: typeof ApiTranscriptionRoute
  ApiTranscriptionConfigRoute: typeof ApiTranscriptionConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slides': {
      id: '/api/slides'
      path: '/api/slides'
      fullPath: '/api/slides'
      preLoaderRoute: typeof ApiSlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slides-config': {
      id: '/api/slides-config'
      path: '/api/slides-config'
      fullPath: '/api/slides-config'
      preLoaderRoute: typeof ApiSlidesConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcription': {
      id: '/api/transcription'
      path: '/api/transcription'
      fullPath: '/api/transcription'
      preLoaderRoute: typeof ApiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcription-config': {
      id: '/api/transcription-config'
      path: '/api/transcription-config'
      fullPath: '/api/transcription-config'
      preLoaderRoute: typeof ApiTranscriptionConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSlidesRoute: ApiSlidesRoute,
  ApiSlidesConfigRoute: ApiSlidesConfigRoute,
  ApiTranscriptionRoute: ApiTranscriptionRoute,
  ApiTranscriptionConfigRoute: ApiTranscriptionConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
